## Interpolation Section

###### Linear Interpolation:          y-y1 / x-x1   =   y2 - y1/x2 -x1

In [55]:
%reset -f
time=[0,20,40,60,80,100]
temp=[26.0,48.6,61.6,71.2,74.8,75.2]

def y(xp,x,y):
    for i,xi in enumerate (x):
        #print("time is %0.2f, temp is %1.2f" %(x[i],y[i]))
        if xp<xi:
            return y[i-1]+ ((y[i]-y[i-1])/(x[i]-x[i-1]))*(xp-x[i-1])
    else:
        return None
        
temp_pt=y(101,time,temp)

if temp_pt is None:
    print("Given x is out of range")
else:
    print("The temperature at given point is %0.3f" %temp_pt)

Given x is out of range


###### Lagrange's Method of Interpolation

In [129]:
%reset -f

time=[0,    20,   40,   60,   80,   100]
temp=[26.0, 48.6, 61.6, 71.2, 74.8, 75.2]



def y(xp,x,y):
    yp=0;n=len(time)
    for i in range(n):
        l=1
        for j in range(n):
            if (j!=i):
                l*=(xp-x[j])/(x[i]-x[j])
        yp += y[i]*l
    return yp
        
                
            
            
        
tx=50        
ty=y(tx,time,temp)
print("pair is %8.2f,%0.2f\t"   %(tx,ty))

pair is    50.00,66.95	


###### Newton Divided Differemce Method for interpolation

In [9]:
%reset -f
import numpy as np
x=[0.0, 1.5, 2.8, 4.4, 6.1, 8.0]
y=[0.0, 0.9, 2.5, 6.6, 7.7, 8.0]
xp=float(input('Enter the value for xp  '))

n=len(x)-1
print(n)
Dy=np.zeros((n+1,n+1))
Dy[:,0]=y


for j in range(n):
    for i in range(j+1,n+1):
        Dy[i,j+1]= (Dy[i,j]-Dy[j,j])/(x[i]-x[j])
print(Dy)

print("****************************************")

yp=Dy[0,0]
for i in range(n):
    p=1
    for j in range(i+1):
        p*=(xp-x[j])
    yp+= p * Dy[i+1,i+1]
print("For x = %0.1f, y = %0.1f" %(xp,yp))

Enter the value for xp  1.9
5
[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.9         0.6         0.          0.          0.          0.        ]
 [ 2.5         0.89285714  0.22527473  0.          0.          0.        ]
 [ 6.6         1.5         0.31034483  0.05316881  0.          0.        ]
 [ 7.7         1.26229508  0.14397719 -0.02463562 -0.04576731  0.        ]
 [ 8.          1.          0.06153846 -0.03148774 -0.02351571  0.01171137]]
***********
For x = 1.9, y = 1.1


In [54]:
% reset -f
import numpy as np
n=5
Dy=np.zeros((n+1,n+1))


for j in range(n+1):
    for i in range(j,n+1):
        Dy[i,j]= 1
print(Dy)

[[ 1.  0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  1.  0.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  1.]]


## Linear Regression Section

###### Linear Regression Method using simple for loop

In [83]:
%reset -f
x=[3,4,5,6,7,8]
y=[0,7,17,26,35,45]
n=len(x)

sumx = sumxy = sumx2 = sumy = 0

for i in range(n):
    sumx += x[i]
    sumxy += x[i]*y[i]
    sumx2 += x[i]**2
    sumy +=y[i]
    
xm = sumx/n
ym = sumy/n

a= (ym*sumx2 - xm*sumxy)/(sumx2 - n* xm**2)
b= (sumxy - xm*sumy)/(sumx2 - n* xm**2)

print("The straight line equation is")
print("y = (%0.2f) + (%0.2f)x" %(a,b))


The straight line equation is
y = (-28.30) + (9.09)x


###### Direct Method with Numpy, Linear Regression

In [90]:
%reset -f
from numpy import array,sum,mean
x=array([3,4,5,6,7,8])
y=array([0,7,17,26,35,45])
n=len(x)


a= (mean(y)*sum(x**2) - mean(x)*sum(x*y)) /( sum(x**2) - n* mean(x)**2 )
b= (sum(x*y) - mean(x)*sum(y))/( sum(x**2) - n* mean(x)**2 )


print("The straight line equation is")
print("y = (%0.2f) + (%0.2f)x" %(a,b))

The straight line equation is
y = (-28.30) + (9.09)x


###### Polynomial of required regression data

In [131]:
%reset -f
import numpy as np
x=np.arange(6)
y=np.array([2,8,14,28,39,62],float)
m=len(x)
n=5   # Degree of polynomial, 2,3,4....
A=np.zeros((n+1,n+1))
B=np.zeros(n+1)
X=np.zeros(n+1)
for i in range(n+1):
    for j in range(n+1):
        if i==0 and j==0:
            A[i,j]=m
            continue
        A[i,j]=np.sum(x**(i+j))
    B[i]=np.sum(x**i * y)
X=np.linalg.solve(A,B)


print("The polynomila is")
print(X[0],"",end='')
for i in range(1,n+1):
    print("   %+f x^%d" %(X[i],i),end='')

The polynomila is
1.99999999992    +22.416667 x^1   -31.458333 x^2   +19.208333 x^3   -4.541667 x^4   +0.375000 x^5

### Interpolation and Curve fitting with Numpy & Scipy

###### Linear, Quadratic,Cubic Interpolation

In [150]:
%reset -f
import numpy as np
from scipy.interpolate import interp1d
x=np.array([3,4,5,6,7,8],float)
y=np.array([0,7,17,26,35,45],float)

f_linear = interp1d(x,y)
f_quad = interp1d(x,y,"quadratic")
f_cubic = interp1d(x,y,"cubic")
print(f_linear(5.12))
print(f_quad(5.12))
print(f_cubic(5.12))

18.080000000000002
18.152541176470592
18.150634666666665


###### Lagrange Interpolation

In [154]:
%reset -f
import numpy as np
from scipy.interpolate import lagrange 
x=np.array([3,4,5,6,7,8],float)
y=np.array([0,7,17,26,35,45],float)

l=lagrange(x,y)
l(6.5)

30.378906249969873

###### Linear Regression

In [157]:
%reset -f
import numpy as np
from scipy.stats import linregress 
x=np.array([3,4,5,6,7,8],float)
y=np.array([0,7,17,26,35,45],float)
l=linregress(x,y)
print(l.intercept,l.slope)

-28.3047619048 9.08571428571


###### Polynomial Curve fitting

In [162]:
%reset -f
import numpy as np
from scipy.optimize import curve_fit 
x=np.array([0,1,2,3,4,5],float)
y=np.array([2,8,14,28,39,62],float)

def f(x,a0,a1,a2,a3):
    return a0 + a1*x**1 + a2*x**2 + a3*x**3
a,_=curve_fit(f,x,y)
print(a)

[  1.92857143e+00   5.67857143e+00  -2.17847962e-12   2.50000000e-01]
