<a id="start"></a>

<span style="padding: 0 05px"></span> [ <font color = "black" size ="3.5" > **Numpy Library Python** <span style = "padding:0 2px"></span>](#ch_1) </font>   <br/>

<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 1 <span style = "padding:0 12px">1D array in Numpy with defined entries</span> ](#ref_1) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 2 <span style = "padding:0 12px">Moving towards 2D array</span> ](#ref_2) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 3 <span style = "padding:0 12px">Array creation methods in numpy</span> ](#ref_3) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 4 <span style = "padding:0 12px">Methods/attributes in Numpy</span> ](#ref_4) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 5 <span style = "padding:0 12px">Element accessing numpy</span> ](#ref_5) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 5 <span style = "padding:0 12px">Loading Data from File</span> ](#ref_6) </font>   <br/>





[Back to Top](#start)

In [509]:
%reset -f
import numpy as np
from sys import getsizeof

### <font color = "navy" >0: space occupied in disk </font> <a id="ref_1"></a>

In [510]:
py_array = [1,2,3,4,5,6,7,9,10]
np_array = np.array(py_array)

<font color = "brown" size ="3.0" > a : Memory size of python list</font>

In [511]:
getsizeof(1) * len(py_array)

252

<font color = "brown" size ="3.0" > b : Memory size of numpy array</font>

In [512]:
# size of one item (element) * number of items in an array
np_array.itemsize * np_array.size

72

### <font color = "navy" >1: 1D array in Numpy with defined entries </font> <a id="ref_1"></a>

In [513]:
array_1 = np.array([1,2,3,4,5,6,7,9])

<font color = "green" size ="2.5" > So inside a ( ) , we insert a Python list., <br>
Means we create numpy array from Python list</font>

In [514]:
array_1

array([1, 2, 3, 4, 5, 6, 7, 9])

- **<font color = 'blue' size ="3.8" >1.1: Include Data Type while defining array</font>**

In [515]:
array_2 = np.array([10,11,12,12], dtype=np.int8)

In [516]:
array_2

array([10, 11, 12, 12], dtype=int8)

<font color = "brown" size ="3.0" > 1.1a : Lets Try a big number with int8</font>

In [517]:
array_3 = np.array([10,11,12,100], dtype=np.int8)

In [518]:
array_3

array([ 10,  11,  12, 100], dtype=int8)

<font color = "brown" size ="3.0" > 1.1b : Try Even bigger with int8</font>

In [519]:
array_4 = np.array([10,11,12,1000], dtype=np.int8)

In [520]:
array_4

array([ 10,  11,  12, -24], dtype=int8)

<font color = "green" size ="2.5" > Look, its wrong.... buz int8 can only handle small number...</font>

<font color = "brown" size ="3.0" > 1.1c : Try with np.int32  or np.int64</font>

In [521]:
array_5 = np.array([1,2,3,10000], dtype=np.int32)
array_6 = np.array([1,2,3,10000], dtype=np.int64)

In [522]:
print(array_5,",",array_6)

[    1     2     3 10000] , [    1     2     3 10000]


<font color = "green" size ="2.5" > Look, size in bites and see the difference</font>

<font color = "brown" size ="3.0" > 1.1d : Accessing 1D array</font>

In [523]:
array_7 = np.array([1,2,3,10000,26,89,21], dtype=np.int32)

In [524]:
i = 5
array_7[i]

89

[Back to Top](#start)

### <font color = "navy" >2: Moving towards 2D array </font> <a id="ref_2"></a>

<font color = "brown" size ="3.0" > 2.1a : Define 2D Numpy array with defined entries </font>

In [525]:
twoD_1 = np.array([[1,2,3,4,5],[10,20,30,40,50]])

<font color = "green" size ="2.5" > So inside a ( ) , we insert a Python nested list, <br>
Means we create numpy array from Python list of lists</font>

In [526]:
twoD_1

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [527]:
twoD_1.dtype

dtype('int64')

In [528]:
twoD_1.shape

(2, 5)

Further Information about all data types available in Numpy<br>
https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

<font color = "green" size ="2.5" > So its 2 rows as defined ... each array is a row and columns are entries</font>

<font color = "brown" size ="3.0" > 2.1b : Accessing 1st row and its elements</font>

In [529]:
twoD_1[0]

array([1, 2, 3, 4, 5])

In [530]:
twoD_1[0][1]

2

<font color = "brown" size ="3.0" > 2.1c : Change specific element in numpy array</font>

In [531]:
twoD_1

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [532]:
twoD_1[0][4]

5

In [533]:
twoD_1[0][4] = 5000

In [534]:
twoD_1

array([[   1,    2,    3,    4, 5000],
       [  10,   20,   30,   40,   50]])

[Back to Top](#start)

### <font color = "navy" >3: Array creation methods in numpy </font> <a id="ref_3"></a>
https://docs.scipy.org/doc/numpy/user/basics.creation.html

<font color = "blue" size ="3.8" >  **Method-1  Conversion from other Python structures (e.g., lists, tuples, distcs)**</font>

<font color = "brown" size ="3.0" > 3.1a : Method-1 , from lists</font>

<font color = "green" size ="3.0" >   all-above example</font>

<font color = "brown" size ="3.0" > 3.1b : Method-1 , from tuples & sets</font>

In [535]:
array_tup = np.array((1,2,3,4,5))
array_tup

array([1, 2, 3, 4, 5])

In [536]:
array_set = np.array({10,20,10,30,20,100,12})
array_set 

array({100, 10, 12, 20, 30}, dtype=object)

<font color = "green" size ="2.5" >   with sets, it take it as an object entries.. so just keep it away for real calculation  <br>**But**<br>It used the set property, no element is repated in set... so quick way to remove duplicates  </font>

<font color = "brown" size ="3.5" > 3.1c : Method-1 , from dicts</font>

In [537]:
# Will come later

<font color = "brown" size ="3.5" > 3.1d : Method-1 , equally spaced 1d arrays</font>

[Back to Top](#start)

<font color = "blue" size ="3.8" >  **Method-2  Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)**</font>

<font color = "brown" size ="2.5" > 3.2a : Method-2 , np.arange() </font>

In [538]:
arr_rng1 = np.arange(3)
arr_rng1

array([0, 1, 2])

In [539]:
arr_rng2 = np.arange(2,5)
arr_rng2

array([2, 3, 4])

In [540]:
arr_rng2 = np.arange(2,5,5)
arr_rng2

array([2])

In [541]:
arr_rng3 = np.arange(1,51,1)

In [542]:
arr_rng3.reshape(10,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

<font color = "green" size ="2.5" >  Only one element buz last element , = step will take it outside the interval  </font>

In [543]:
arr_rng3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

<font color = "green" size ="2.5" >  In case, we want to get back 1D  </font>

In [544]:
arr_rng4 = np.arange(2,15,5)
arr_rng4

array([ 2,  7, 12])

In [545]:
arr_rng5 = np.arange(1,1.5,0.1)
arr_rng5

array([1. , 1.1, 1.2, 1.3, 1.4])

<font color = "green" size ="2.5" >  User decide the step, not the number of element.. and thats the difference between this and below </font>

<font color = "brown" size ="2.5" > 3.2(b) : Method-2 , np.linspace() </font>

In [546]:
lin_1 = np.linspace(1,2)
lin_1

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

<font color = "green" size ="2.5" >  Equispaced numbers between start and stop, default step is 50, </font>

In [547]:
lin_2 = np.linspace(1,20,num = 10)
lin_2

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

<font color = "green" size ="2.5" >  User decides the number of element with <code>num = n</code> not the delta  </font>

<font color = "brown" size ="3.0" > 3.2(c) : Method-2 , zeros only</font>

In [548]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<font color = "green" size ="2.5" > We mention the shape as a tuple and then it generates </font>

In [549]:
zeros.shape

(2, 5)

In [550]:
zeros.dtype

dtype('float64')

<font color = "green" size ="2.5" >   inside np.zeros() is a tuple., and it defines the dimensions of numpy array </font>

<font color = "brown" size ="3.0" > 3.2(d) : Method-2 , empty array</font>

In [551]:
empty = np.empty((4,6))
empty

array([[4.9e-324, 9.9e-324, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [1.5e-323, 2.0e-323, 2.5e-323, 3.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 3.5e-323, 4.0e-323, 4.9e-323, 5.4e-323],
       [4.9e-323, 5.4e-323, 5.9e-323, 6.4e-323, 5.9e-323, 6.4e-323]])

<font color = "green" size ="2.5" >   Do not use it... thats all </font>

<font color = "brown" size ="3.0" > 3.2(e) : Method-2 , Identity matrix</font>

In [552]:
iden = np.identity(5)
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [553]:
iden.shape

(5, 5)

[Back to Top](#start)

<font color = "brown" size ="3.0" > 3.2(f) : Method-2 , .full_like() methdo for array creation</font>

In [554]:
np.full_like(iden,0)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<font color = "brown" size ="3.0" > 3.2(f) : Method-2 , Initialize random decimal numbers</font>

In [555]:
np.random.rand(4,2)

array([[0.87542244, 0.52439923],
       [0.4315439 , 0.03850102],
       [0.34278565, 0.69041434],
       [0.05239858, 0.00563527]])

<font color = "brown" size ="3.0" > 3.2(g) : Method-2 , Initialize random decimal numbers with same shaoe</font>

In [556]:
np.random.random_sample(iden.shape)

array([[8.39862962e-01, 7.09808540e-01, 1.67336606e-01, 4.11867669e-01,
        8.46751358e-01],
       [9.19503321e-01, 5.94650465e-01, 3.58058380e-01, 7.45626823e-01,
        9.71184338e-01],
       [9.88890586e-02, 4.40466832e-01, 1.11842633e-04, 9.94237177e-01,
        3.68717347e-01],
       [5.02640070e-01, 4.45812252e-01, 7.35142214e-01, 4.19182337e-01,
        4.53085717e-01],
       [9.39495729e-01, 8.60427526e-01, 2.04846231e-01, 8.97254030e-02,
        3.81604974e-01]])

<font color = "brown" size ="3.0" > 3.2(h) : Method-2 , Random integer values</font>

In [557]:
np.random.randint(low = 1,high=10, size = (3,3))

array([[5, 3, 1],
       [2, 7, 4],
       [5, 8, 8]])

<font color = "brown" size ="3.0" > 3.2(i) : Method-2 , Initialize the quiz.. array</font>

In [558]:
quiz = np.ones(shape=(5,5))
quiz

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [559]:
quiz[1:-1,[1,2,3]] = 0
# This is equal to the following:
# quiz[1:-1,1] = 0
# quiz[1:-1,3] = 0
# quiz[1:-1,2] = 0

In [560]:
quiz

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [561]:
quiz[2,2] = 9

In [562]:
quiz

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

<font color = "brown" size ="3.0" > 3.2(j) : Method-2 , Initialize the quiz.. array</font>

In [563]:
cpy_1 = [1,2,3,4]
cpy_2 = cpy_1
cpy_2

[1, 2, 3, 4]

In [564]:
cpy_2[0] = 1000
cpy_2

[1000, 2, 3, 4]

In [565]:
cpy_1

[1000, 2, 3, 4]

In [566]:
cpy_2 = cpy_1.copy()
cpy_2

[1000, 2, 3, 4]

In [567]:
cpy_2[0] = 165282
cpy_2

[165282, 2, 3, 4]

In [568]:
cpy_1

[1000, 2, 3, 4]

### <font color = "navy" >4: Methods/attributes in Numpy </font> <a id="ref_4"></a>
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

<font color = "green" size ="3.5" >  "axis 0" along rows <br> "axis 1" along columns </font>

In [569]:
x = [[4,1,3],[3,2,6],[7,8,9]]
twoD_2 = np.array(x)
twoD_2

array([[4, 1, 3],
       [3, 2, 6],
       [7, 8, 9]])

<font color = "brown" size ="3.0" > 4.1(a) : sum along rows and columns</font>

In [570]:
twoD_2.sum(axis = 0)

array([14, 11, 18])

In [571]:
twoD_2.sum(axis = 1)

array([ 8, 11, 24])

<font color = "brown" size ="3.0" > 4.1(b) : Transpose</font>

In [572]:
twoD_2.T

array([[4, 3, 7],
       [1, 2, 8],
       [3, 6, 9]])

<font color = "brown" size ="3.0" > 4.1(C) : Get Iterator</font>

In [573]:
twoD_2.flat

In [574]:
for item in twoD_2.flat:
    print(item)

4
1
3
3
2
6
7
8
9


<font color = "brown" size ="3.0" > 4.1(d) : See the dimension and shape</font>

In [575]:
twoD_2.ndim

2

In [576]:
twoD_2.shape

(3, 3)

In [577]:
twoD_2.size

9

<font color = "brown" size ="3.0" > 4.1(d) : Total bytes consumed (Your elements of array)</font>

In [578]:
twoD_2.nbytes

72

<font color = "brown" size ="3.0" > 4.1(d) : Index of maximum/minimum element</font>

In [579]:
twoD_2

array([[4, 1, 3],
       [3, 2, 6],
       [7, 8, 9]])

In [580]:
twoD_2.argmin()

1

In [581]:
twoD_2.argmax()

8

<font color = "green" size ="2.5" >   For 1D is easy to see, but for 2D .. HOw??? <br>
its the index of flat array, e.g. by using .ravel <br>
But <br>
If I also pass the "axis = 0/1" key to the argmax() then
</font>

In [582]:
twoD_2.argmax(axis = 0)

array([2, 2, 2])

In [583]:
twoD_2.argmax(axis = 1)

array([0, 2, 2])

<font color = "green" size ="2.5" >   The index of max/min along row/column
</font>

<font color = "brown" size ="3.0" > 4.1(e) : Indices of sorted array</font>

In [584]:
array_8 = np.array([5,1,3,4,10,2,20])
array_8

array([ 5,  1,  3,  4, 10,  2, 20])

In [585]:
array_8.argsort()

array([1, 5, 2, 3, 0, 4, 6])

In [586]:
twoD_2

array([[4, 1, 3],
       [3, 2, 6],
       [7, 8, 9]])

In [587]:
twoD_2.argsort(axis = 0) # with axis =1 , I feel bit-tough

array([[1, 0, 0],
       [0, 1, 1],
       [2, 2, 2]])

[Back to Top](#start)

<font color = "brown" size ="3.0" > 4.1(i) : Stacking of arrays</font>

In [600]:
print(array_7)
print(array_8)

[    1     2     3 10000    26    89    21]
[ 5  1  3  4 10  2 20]


In [601]:
np.vstack([array_7,array_8])

array([[    1,     2,     3, 10000,    26,    89,    21],
       [    5,     1,     3,     4,    10,     2,    20]])

In [602]:
np.hstack([array_7,array_8])

array([    1,     2,     3, 10000,    26,    89,    21,     5,     1,
           3,     4,    10,     2,    20])

In [598]:
np.vstack([array_7,array_8,array_7,array_7])

array([[    1,     2,     3, 10000,    26,    89,    21],
       [    5,     1,     3,     4,    10,     2,    20],
       [    1,     2,     3, 10000,    26,    89,    21],
       [    1,     2,     3, 10000,    26,    89,    21]])

<font color = "blue" size ="3.8" >  **2:  Some built albegra Operations in Numpy**</font>

In [264]:
twoD_3 = np.array([[1,0,1],[0,0,1],[1,1,1]])

In [265]:
twoD_2

array([[4, 1, 3],
       [3, 2, 6],
       [7, 8, 9]])

In [266]:
twoD_3

array([[1, 0, 1],
       [0, 0, 1],
       [1, 1, 1]])

<font color = "brown" size ="3.0" > 4.2(a) : plus</font>

In [267]:
twoD_2 + twoD_3

array([[ 5,  1,  4],
       [ 3,  2,  7],
       [ 8,  9, 10]])

<font color = "brown" size ="3.0" > 4.2(b) : multiply, **element by element only** </font>

In [268]:
twoD_2 * twoD_3

array([[4, 0, 3],
       [0, 0, 6],
       [7, 8, 9]])

<font color = "brown" size ="3.0" > 4.2(c) : square root of whole matrix </font>

In [269]:
np.sqrt(twoD_2)

array([[2.        , 1.        , 1.73205081],
       [1.73205081, 1.41421356, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

<font color = "brown" size ="3.0" > 4.2(c) : **.where method** </font>

In [270]:
twoD_2

array([[4, 1, 3],
       [3, 2, 6],
       [7, 8, 9]])

In [271]:
np.where(twoD_2> 8)

(array([2]), array([2]))

<font color = "green" size ="2.5" >   It returns a tuple, ( row , columns ) ; this is the simples case.. now move to <br> condition > smaller number
</font>

In [272]:
type(np.where(twoD_2> 8))

tuple

In [273]:
np.where(twoD_2 > 7)

(array([2, 2]), array([1, 2]))

<font color = "green" size ="2.5" >   Read it as : thi is a tuple ... <br>
**( all row index , all column index )** <br>
</font>

In [274]:
np.where(twoD_2> 6)

(array([2, 2, 2]), array([0, 1, 2]))

In [275]:
np.where(twoD_2> 5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

[Back to Top](#start)

### <font color = "navy" >5: Element Accessing </font> <a id="ref_5"></a>


In [276]:
%reset -f
import numpy as np
from sys import getsizeof

<font color = "blue" size ="3.8" >  **1:  2D**</font>

In [298]:
a = [[1,2,3,4,5,6,7,8],[11,12,13,14,15,16,17,18],[11,12,13,14,15,16,17,18]]
a = np.array(a)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 13, 14, 15, 16, 17, 18],
       [11, 12, 13, 14, 15, 16, 17, 18]])

<font color = "brown" size ="3.0" > 5.1(a) : Get specific element </font>

In [299]:
# get sped
a[0][4]

5

In [300]:
a[0,4]

5

<font color = "brown" size ="3.0" > 5.1(b) : Get specific Row </font>

In [301]:
a[1][:]

array([11, 12, 13, 14, 15, 16, 17, 18])

<font color = "brown" size ="3.0" > 5.1(b) : Get specific Column </font>

In [302]:
a[:,0]

array([ 1, 11, 11])

In [303]:
a[:,1]

array([ 2, 12, 12])

<font color = "brown" size ="3.0" > 5.1(b) : Get with step size </font>

In [304]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 13, 14, 15, 16, 17, 18],
       [11, 12, 13, 14, 15, 16, 17, 18]])

In [305]:
a[0,2::2]

array([3, 5, 7])

<font color = "brown" size ="3.0" > 5.1(b) : Accessing specific portion in 2d matrix</font>

<font color = "green" size ="2.5" >   Take the zeroth row, <br>
    start from 2nd column to 7th, <br>
    with steo size of 2
</font>

In [374]:
a

array([[1000,    2,    3,    4,    5,    6,    7,    8],
       [ 100,   12,   13,   14,   15,   16,   17,   18],
       [  10,   12,   13,   14,   15,   16,   17,   18]])

In [375]:
a[[0,1,2],0]

array([1000,  100,   10])

<font color = "green" size ="2.5" >   This is accessing the [0,1,2] row with "0th" column
</font>

In [373]:
a[[0,1,2],[0,1,2]]

array([1000,   12,   13])

<font color = "green" size ="2.5" >   Borth are list, so take **first-list as row & second-list as column index** 
</font>

In [377]:
a[[0,1,2],2:5]

array([[ 3,  4,  5],
       [13, 14, 15],
       [13, 14, 15]])

<font color = "green" size ="3.5" >   **Similarly for columns as well..** 
</font>

<font color = "brown" size ="3.0" > 5.1(b) : Changing the while columns e.g.</font>

In [378]:
a

array([[1000,    2,    3,    4,    5,    6,    7,    8],
       [ 100,   12,   13,   14,   15,   16,   17,   18],
       [  10,   12,   13,   14,   15,   16,   17,   18]])

In [379]:
a[:,0] 

array([1000,  100,   10])

In [380]:
# we can give a single value
a[:,0]  = 0

In [381]:
a[:,0] 

array([0, 0, 0])

In [382]:
# Or we can give a list of values
a[:,0]

array([0, 0, 0])

In [383]:
a[:,0] = [1000,100,10]

In [314]:
a

array([[1000,    2,    3,    4,    5,    6,    7,    8],
       [ 100,   12,   13,   14,   15,   16,   17,   18],
       [  10,   12,   13,   14,   15,   16,   17,   18]])

<font color = "blue" size ="3.8" >  **2:  3D**</font>

In [390]:
b = [
    [[1,2,1,2]  , [3,4,3,4]],  # a 2d list
    [[5,6,5,6]  , [7,8,7,8]],  # a 2d list
    [[10,11,10,11]    , [12,13,12,13]],
    ]



    
b = np.array(b)

In [391]:
b.shape

(3, 2, 4)

In [393]:
b

array([[[ 1,  2,  1,  2],
        [ 3,  4,  3,  4]],

       [[ 5,  6,  5,  6],
        [ 7,  8,  7,  8]],

       [[10, 11, 10, 11],
        [12, 13, 12, 13]]])

<font color = "green" size ="2.5" >    **We have 3 arrays, each of them is (2,4)** 
</font>

<font color = "brown" size ="3.0" > 5.2(a) : Get specific element in 3d</font>

In [396]:
# first get the right array
b[1]

array([[5, 6, 5, 6],
       [7, 8, 7, 8]])

In [399]:
# now go to the position
# b[1,0,1] or better to write
b[1][0][1]

6

<font color = "brown" size ="3.0" > 5.2(a) : Get specific portion from 3d</font>

In [400]:
b

array([[[ 1,  2,  1,  2],
        [ 3,  4,  3,  4]],

       [[ 5,  6,  5,  6],
        [ 7,  8,  7,  8]],

       [[10, 11, 10, 11],
        [12, 13, 12, 13]]])

In [414]:
b[0:3,0,0]

array([ 1,  5, 10])

In [431]:
b[0:3,0:2,0]

array([[ 1,  3],
       [ 5,  7],
       [10, 12]])

In [432]:
b[0:3,0:2,0:2]

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[10, 11],
        [12, 13]]])

<font color = "brown" size ="3.0" > 5.2(a) : Get specific portion with loop</font>

In [433]:
b

array([[[ 1,  2,  1,  2],
        [ 3,  4,  3,  4]],

       [[ 5,  6,  5,  6],
        [ 7,  8,  7,  8]],

       [[10, 11, 10, 11],
        [12, 13, 12, 13]]])

In [452]:
for i in [0,1,2]:
    for j in range(2):
        for k in range(1):
            print(i,j,k, b[i,j,k])
        

0 0 0 1
0 1 0 3
1 0 0 5
1 1 0 7
2 0 0 10
2 1 0 12


In [453]:
for i in [0,1,2]:
    for j in range(2):
        for k in range(1):
            print(i,j,k, b[i][j][k])

0 0 0 1
0 1 0 3
1 0 0 5
1 1 0 7
2 0 0 10
2 1 0 12


[Back to Top](#start)

### <font color = "navy" >6: Load Data from file </font> <a id="ref_6"></a>
